name: edo
description: development, startups and something else
meta_description: "Your New Jekyll Site, Blogging about stuffs"

gems: [jekyll-paginate, jekyll-gist]

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://edo.so'
google_analytics: 'UA-57918031-1'

# Details for the RSS feed generator
url:            'https://edo.so'
author:         'Edoardo Biraghi'
